#! /bin/bash

pgrep -x sxhkd > /tmp/ || sxhkd &

xrandr --output HDMI-2 --mode 1920x1080 --rotate normal --rate 75.00 --output HDMI-1 --mode 1920x1080 --rotate normal --rate 60.00 --left-of HDMI-2 &

pacmd set-default-sink 1 &

xsetwacom --set "Wacom One by Wacom S Pen stylus" MapToOutput HDMI-A-1 &
xsetwacom --set "Wacom One by Wacom S Pen stylus" Rotate half &

bspc config automatic_scheme longest
bspc monitor HDMI-2 -d 6 7 8 9 0  
bspc monitor HDMI-1 -d 1 2 3 4 5 
bspc config border_width        5
bspc config window_gap          2

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Vivaldi-stable desktop=1
bspc rule -a discord desktop=2
bspc rule -a Com.github.xournalpp.xournalpp desktop=7
bspc rule -a codium desktop=0
bspc rule -a obsidian desktop=9
bspc rule -a Terraria.bin.x86_64 desktop =8

bspc config focused_border_color \#0FFF00
bspc config active_border_color  \#e91284
bspc config normal_border_color \#e91284

bspc config focus_follows_pointer true

# Fix cursor
xsetroot -cursor_name left_ptr
